name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      
    - name: Show directory inside subdir
      run: ls
    # - name: Build the Docker image
    #   # run: docker build -t . --file Dockerfile --tag sushantao/django-git:$(date +%s)
    #   run: docker build -t . --file Dockerfile --tag sushantao/django-git:latest

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: sushantao
        password: ${{ secrets.DOCKERHUB_TOKEN }} 
        
    - name: Build and Push to docker hub
      uses: docker/build-push-action@v6
      with:
        context: ./app
        file: ./app/Dockerfile
        push: true
        tags: sushantao/django-git:latest
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: SSH into EC2 instance
        env: 
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{secrets.SSH_HOST}}
          USER_NAME: ${{secrets.USER_NAME}}
        run: |
          pwd
          echo "$PRIVATE_KEY" > private_key
          chmod 600 private_key
          ssh -tt -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME}
          sudo apt-get update -y
          # sudo apt-get install git -y

          cd /home/${USER_NAME}
          echo "Line 55: Current working directory is $(pwd)"
          if [ ! -d "django-git" ]; then
            git clone https://github.com/sushantaojha/django-git.git
          else
            cd django-git && git pull origin main
          fi
          echo "Line 61: Current working directory is $(pwd)"

          # Change to the repo directory and pull the Docker images
          cd /home/${USER_NAME}/django-git

          docker compose up -d
