name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
# new push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    
    # - name: Build the Docker image
    #   # run: docker build -t . --file Dockerfile --tag sushantao/django-git:$(date +%s)
    #   run: docker build -t . --file Dockerfile --tag sushantao/django-git:latest

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: sushantao
        password: ${{ secrets.DOCKERHUB_TOKEN }} 
        
    # - name: Push to docker hub
    #   uses: docker/build-push-action@v6
    #   with:
    #     push: true
    #     tags: sushantao/django-git:latest
        
    - name: Show directory inside subdir
      run: pwd
      
    - name: Build and Push to docker hub
      uses: docker/build-push-action@v6
      with:
        context: ../../app
        file: ../../app/Dockerfile
        push: true
        tags: sushantao/django-git:latest
